### ISSUE TITLE
node.subtrees() and node.hasSubtree(otherNode) Definition

### ISSUE THREAD

**Issue by glennDittmann** [Scalified/tree#15]
Hey guys, 
first of all great work on the library, it is really well done! 

I was coming across two ambiguities. But first, let's introduce an example.
There are two trees **1** and **2** looking like this (according to the `node.toString()` method):

**Tree1**:
```
+- B
|  +- A
```

**Tree2**:
```
+- F
|  +- E
|  |  +- D
|  |  |  +- C
|  |  +- B
|  |  |  +- A
```
My first question is regarding the definition of a subtree. [In general](https://en.wikipedia.org/wiki/Tree_(data_structure)#Terminology) I think a subtree is **any** node in a tree and all of its descendants. So to my understanding **Tree2** should have five subtrees. However, when I called `n8.subtrees()` (building the subtrees for **Tree2**) the resulting collection is of size one and only contains this single subtree:
**Subtree2**
```
+- E
|  +- D
|  |  +- C
|  +- B
|  |  +- A
```
This leads to my second question. Basically checking, whether **Tree1** is a subtree of **Tree2** (`n8.hasSubtree(n2)` ,s. code below) yields `false`. However, to me **Tree1** clearly is a subtree of **Tree2**.

I do assume, that comparison for subtrees is made with the data contained in the nodes and not the memory addresses the individual objects/pointers are stored.

Interestingly when computing the subtrees for **Subtree2** I get:
**Subtree2.1**
```
+- D
|  +- C
```
and
**Subtree2.2**
```
+- B
|  +- A
```

So I am supposed to iterate the function `subtrees()` for all nodes in a tree to really get all subtrees ? If so, then I would suggest adding a function, that does this. 
And I still think `hasSubtree()` needs a fix. Because, even `n2.equals(n4)` yields `false`....

Sorry for the long post. And thanks in advance for taking a look into it. 

Best regards, 
Glenn

For reference the code that I executed on my machine, maybe the solution lies there:
```
TreeNode<String> n1 = new ArrayMultiTreeNode<>("A");
TreeNode<String> n2 = new ArrayMultiTreeNode<>("B");

TreeNode<String> n3 = new ArrayMultiTreeNode<>("A");
TreeNode<String> n4 = new ArrayMultiTreeNode<>("B");
TreeNode<String> n5 = new ArrayMultiTreeNode<>("C");
TreeNode<String> n6 = new ArrayMultiTreeNode<>("D");
TreeNode<String> n7 = new ArrayMultiTreeNode<>("E");
TreeNode<String> n8 = new ArrayMultiTreeNode<>("F");

// Assigning tree nodes
n2.add(n1);

n8.add(n7);
n7.add(n6);
n7.add(n4);
n6.add(n5);
n4.add(n3);


// subtrees
Collection<? extends TreeNode<String>> subtrees2 = n2.subtrees();
Collection<? extends TreeNode<String>> subtrees8 = n8.subtrees();
System.out.println("Size of subtrees8: " + subtrees8.size());
System.out.println();

System.out.println("Tree 1:");
System.out.println(n2.toString());
System.out.println();
System.out.println("Tree 2:");
System.out.println(n8.toString());

System.out.println("Printing each subtree of the two trees.");
System.out.println("Tree 1:");
for (TreeNode<String> tree : subtrees2) {
	System.out.println(tree.toString());
}
System.out.println("Tree 1:");
for (TreeNode<String> tree : subtrees8) {
	System.out.println(tree.toString());
}


System.out.println(n8.hasSubtree(n2));
System.out.println(n2.equals(n4)); 
```

**Comment by vbaidak** [comment]
Hello, @glennDittmann !
Thanks for reaching out!

Yes, you're absolutely correct regarding the terminology. Moreover, the `subtree` term description in the [Terminology](https://github.com/Scalified/tree#terminology) is the same as you pointed out.

However, I need to shed some light on the core things of how the `tree` library works. Each [`TreeNode`](https://github.com/Scalified/tree/blob/master/tree/src/main/java/com/scalified/tree/TreeNode.java) is itself a tree, meaning it can have children, which in turn are also `trees` or `leaves`. So, in the case of a concrete node within the tree, be it `root` or `leaf` or `in-the-middle` of a tree, it is already a `subtree` (if we want to interpret things in accordance to terminology). If we are talking about implementation, you don't need to have any additional `subtree` method on a [`TreeNode`](https://github.com/Scalified/tree/blob/master/tree/src/main/java/com/scalified/tree/TreeNode.java) since it is already a subtree (a `node` with all of its `descendants`)

On the other hand, the `subtrees` method *returns the collection of the child nodes of the current node with all of its proper descendants, if any* as **Javadoc** points out. This is just a handy method for getting a flat collection of children.

Regarding `hasSubtree` and `equality` checks, the library doesn't compare the `data` inside nodes. This is by specification - we don't want to rely on the unknown data provided by the user. Instead, the library assigns each [`TreeNode`](https://github.com/Scalified/tree/blob/master/tree/src/main/java/com/scalified/tree/TreeNode.java) a unique identifier during instantiation and use it for the `equality` checks. So, in your case, these 2 different trees instantiated separately will return `false` when checking for `equality`. If you really need to check and compare `data` within the tree, you can extend one of the implementations: either [ArrayMultiTreeNode](https://github.com/Scalified/tree/blob/master/tree/src/main/java/com/scalified/tree/multinode/ArrayMultiTreeNode.java) or [LinkedMultiTreeNode](https://github.com/Scalified/tree/blob/master/tree/src/main/java/com/scalified/tree/multinode/LinkedMultiTreeNode.java) and override `equals` method

Hope this helps

**Comment by glennDittmann** [comment]
Hey @vbaidak,
thanks for the quick answer and your detailed help. 
I see, I understand the design choices here, makes sense and also should make the task I want to solve more easy. 

> If you really need to check and compare data within the tree, you can extend one of the implementations: either [ArrayMultiTreeNode](https://github.com/Scalified/tree/blob/master/tree/src/main/java/com/scalified/tree/multinode/ArrayMultiTreeNode.java) or [LinkedMultiTreeNode](https://github.com/Scalified/tree/blob/master/tree/src/main/java/com/scalified/tree/multinode/LinkedMultiTreeNode.java) and override equals method

That's also a good idea, thanks!
