### ISSUE TITLE
Leaf Node Determination

### ISSUE THREAD

**Issue by amitjoy** [Scalified/tree#5]
If I am not wrong, if a node adds an edge to itself, it should be considered as a leaf node since it doesn't have any children.

But according to the following snippet, it is different.

```java
        final TreeNode<String> node = new ArrayMultiTreeNode<>("a");
        node.add(node);

        System.out.println(node.isLeaf()); //return false
```

I think it should be set configurable if the same node can be considered a child to itself.

**Comment by vbaidak** [comment]
Hi @amitjoy !
Thanks for using Scalified tree library.

Regarding your question, could you please provide more details on your case?

Adding a node reference to itself as a child seems a bit weird to me since it has no sense and, moreover, it would result in **StackOverflowError** when performing operations. Consider the similar case with Java collections:

```java
Set<Set> set = new HashSet<>();
set.add(set);
set.hashCode(); // java.lang.StackOverflowError
```

**Comment by vbaidak** [comment]
Although, I'm not very aware of OSGi, it looks like checking the equality here is a required step.

The initial idea of the **library** was to complement the missing Tree stuff in Java, so the behavior is very similar to original Java collections.

I could add some sort of restriction to deny such operations (like throwing an exception in such cases), but still, Java Collections allow it and thus this should not be restricted.
