### ISSUE TITLE
how to build tree with    HashSet<Leaf node id> ?

### ISSUE THREAD

**Issue by 287138531** [Scalified/tree#8]
i have a  HashSet<>  ,key  is all the  Leaf node  id.  and  i  can get the  pId to.
can i use  this to build a tree ?

**Comment by vbaidak** [comment]
Hi @287138531 ,

Thanks for using <b>Scalified Tree Library</b>!

For building the tree, please refer [Documentation](https://github.com/Scalified/tree) section [Creation](https://github.com/Scalified/tree#creation)

**Comment by 287138531** [comment]
> Hi @287138531 ,
> 
> Thanks for using Scalified Tree Library!
> 
> For building the tree, please refer [Documentation](https://github.com/Scalified/tree) section [Creation](https://github.com/Scalified/tree#creation)

...the exp is to simple. can get me any tips?

**Comment by vbaidak** [comment]
In order to provide you a meaningful help, we need to know the concrete case and troubles you are facing with. Please provide your case: description, sample code, what you are trying to achieve etc.

Also, it would be great if you could clarify what exactly seems to be not covered by [Original Documentation](https://github.com/Scalified/tree).
